# Generated by Django 5.2.5 on 2026-09-15 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва рецепта')),
                ('description', models.TextField(verbose_name='Короткий опис')),
                ('ingredients', models.TextField(verbose_name='Інгредієнти')),
                ('instructions', models.TextField(verbose_name='Кроки приготування')),
                ('cooking_time', models.PositiveIntegerField(help_text='Час у хвилинах', verbose_name='Час приготування')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Зображення страви')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепти',
                'ordering': ['-created_at'],
            },
        ),
    ]
