# Generated by Django 5.2.5 on 2026-09-29 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipe_category_recipe_likes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легко'), ('medium', 'Середньо'), ('hard', 'Складно')], default='easy', max_length=10, verbose_name='Складність'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Сніданки'), ('lunch', 'Обіди'), ('dinner', 'Вечері'), ('dessert', 'Десерти'), ('drinks', 'Напої')], default='lunch', max_length=20, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Головне зображення страви'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(verbose_name='Інгредієнти (кожен з нового рядка)'),
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Номер кроку')),
                ('description', models.TextField(verbose_name='Опис кроку')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_steps/', verbose_name='Фото кроку')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main.recipe')),
            ],
            options={
                'verbose_name': 'Крок приготування',
                'verbose_name_plural': 'Кроки приготування',
                'ordering': ['step_number'],
            },
        ),
    ]
